### ISSUE TITLE
[Bot/Bug]: Plugin - Chat to discord

### ISSUE THREAD

**Issue by 599ms** [MinecraftBot-com/MineBot-V3-Issues#10]
### Current Behavior

When I try and send a message in the chat it sends a weird request via web hook.

The error - 
![image](https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/60bff3c0-a013-4cdc-91fb-79566ee713a4)

How it looks in game - 
![image](https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/90e84e23-c6fe-46eb-b82f-c86133eaf0bd)

I am fy2 and it only shows when I type in chat.

### Expected Behavior

It should just say like the other messages but it somehow gets confused when I (The Bot controller) is typing.

### Steps To Reproduce

Fix the message of the owner.

### Screenshots

Error - https://cdn.discordapp.com/attachments/1212429733523099712/1229437825095569453/image.png?ex=662fae33&is=661d3933&hm=af68a52a63943d55f9560e2aa68be39c046db2d8f0924785925726b067eeb920&

Ingame chat - https://cdn.discordapp.com/attachments/1212429733523099712/1229437873695100948/image.png?ex=662fae3e&is=661d393e&hm=b63ea8c14cfe5ae878e7f6625ed7a7b2146c7bc887f08d4cb2ce6f03a0351cf8&

### Profile/Snapshot

Reporting user support id: - 0-rjf8e96k

Reporting profile id: - 661d2b683f4b050282fb6c57

Profile snapshot: - ?

**Comment by OnlyQubes** [comment]
Perfect bug report, thank you very much.

Just in case you modify your current profile, could you send me the server address on Discord (or post it here publicly if you don't mind that), as while this is not fully server specific, it would still be good to test the fix against this specific server.

**Comment by 599ms** [comment]
Yeah I used "combocraft.dk" as my server.

**Comment by OnlyQubes** [comment]
Fixed in build #b-2024-04-16-a
