### ISSUE TITLE
[Bot/Bug]: Accounts not logging in and not giving any error logs

### ISSUE THREAD

**Issue by mika0305** [MinecraftBot-com/MineBot-V3-Issues#11]
### Current Behavior

I have 8 accounts in the list after 5 it doesn't put any more online. It doesn't show any errors in the logger
I saw it connecting a few times in the accounts list but it goes back to offline after 0.5s probably getting blocked after a few attempts

### Expected Behavior

I want it to log all accounts on in the list

### Steps To Reproduce

Simply press start in the profile and wait a little it will put 5 online and stops 

### Profile/Snapshot

Reporting user support id: - 0-d8v776ip

Reporting profile id: - 661d4cfb3f4b050282fb6f2c

Profile snapshot: - its set to auto but probably picks 1.20 or higher.

**Comment by OnlyQubes** [comment]
Looking into the bug right now, could you please provide the address of the server please, can't seem to find it in our previous conversations.

**Comment by OnlyQubes** [comment]
Sadly can't reproduce the issue right now, seems like it has resolved it self. I have added more debug code, so that in the future if it happens we can detect it and properly analyze it.

Keeping the ticket open, in case it pops up again.

**Comment by yemix** [comment]
Maybe ip limit
