### ISSUE TITLE
[Bot/Bug]:  Can't use arrow keyboard on web pages

### ISSUE THREAD

**Issue by WUWOAOWUW** [MinecraftBot-com/MineBot-V3-Issues#12]
### Current Behavior

Can't use arrow keyboard

### Expected Behavior

*No response*

### Steps To Reproduce

*No response*

### Screenshots

[https://gyazo.com/5b289dc57f085a9bd91d3b3f5bf4e070](https://gyazo.com/5b289dc57f085a9bd91d3b3f5bf4e070)
Server Address Settings work!! : [https://gyazo.com/16099325a601dbf9e11fcac04c715f36](https://gyazo.com/16099325a601dbf9e11fcac04c715f36)
*No response*

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

### Additional Context

**Comment by OnlyQubes** [comment]
Fixed in build #b-2024-04-16-a
