### ISSUE TITLE
[Web/Bug]: Compass

### ISSUE THREAD

**Issue by WUWOAOWUW** [MinecraftBot-com/MineBot-V3-Issues#13]
### Current Behavior

i can't look Navigation Item

### Screenshots

![image](https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/167145792/63888fc9-7dd5-41bf-ac37-812db999f1ba)

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Opened a more generic ticket for this issue: #14 

Current issue displayed in the screenshot is due to the mapping data not being generated for earlier minecraft versions (please re-open the ticket if this is happening on a profile that has 1.19+ protocol selected)
