### ISSUE TITLE
[Web/Bug]: logo

### ISSUE THREAD

**Issue by WUWOAOWUW** [MinecraftBot-com/MineBot-V3-Issues#15]
### Current Behavior

I changed server IP but my profile picture didn't change

### Screenshots

![image](https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/167145792/54de3157-5899-4536-a9c2-f97a668bbffa)

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Fixed in build #b-2024-04-24-a
