### ISSUE TITLE
[Feature]: in-game chat

### ISSUE THREAD

**Issue by WUWOAOWUW** [MinecraftBot-com/MineBot-V3-Issues#16]
### Description

![image](https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/167145792/ef147774-c116-49fa-a087-8e735ac49b88)
 try add in-game chat on web :blush: 

### Suggested Solution

a

### Alternatives

a

### Additional Context

a

**Comment by OnlyQubes** [comment]
Would this be different from the bot's chat view? Or is there a clarity issue, where you didn't even know/notice that you can view the bot's chat:

![image](https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/13767563/351d664b-f122-41bc-8d2a-d9dbf812d76f)

**Comment by OnlyQubes** [comment]
Clarified issue in Discord pms:
It is not clear for new users that they need (or can) click on the bot's face to select it, for the right hand side menu.

**Comment by OnlyQubes** [comment]
Fixed in build #b-2024-04-24-a
