### ISSUE TITLE
[Web/Bug]: Chat Command weird

### ISSUE THREAD

**Issue by WUWOAOWUW** [MinecraftBot-com/MineBot-V3-Issues#17]
### Screenshots

https://gyazo.com/bfde2bfa809e70d82c0aa3be5b20f589

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Refactored how Settings are loaded, validated, transmitted, handled for profiles in patch `pre-prod-2024-07-26a`, hopefully this issue is resolved.
