### ISSUE TITLE
[Bot/Bug]: Area Miner does not work

### ISSUE THREAD

**Issue by 599ms** [MinecraftBot-com/MineBot-V3-Issues#19]
### Current Behavior

Does nothing on enable the plugin

### Expected Behavior

It should mine

### Screenshots

<img width="1021" alt="image" src="https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/d3322893-a87e-40e9-85d5-2f1b8ca74c47">

Settings 
<img width="815" alt="image" src="https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/3e918943-3157-4c47-acc6-68158cb8a31e">

Ingame
<img width="1552" alt="image" src="https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/d02274a1-a98c-4b24-a080-ac10c8008b72">

### Profile/Snapshot

Reporting user support id: - 0-rjf8e96k

Reporting profile id: - 661d2b683f4b050282fb6c57

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Ah sorry for that, forgot to disable Area Miner. It's just a placeholder now, as it was not re-implemented for the beta. Will be added later.
