### ISSUE TITLE
[Bot/Bug]: Cannot start "Follower" plugin after I stopped "Area miner"

### ISSUE THREAD

**Issue by 599ms** [MinecraftBot-com/MineBot-V3-Issues#20]
### Current Behavior

The bot cannot start the plugin 'Follower' after I have pressed "Stop and Delete' on my 'Area miner' Plugin.

Server was 'mc.onlineklubben.dk' and was using 1.20.4

### Expected Behavior

It should start the plugin 'Follower'

### Steps To Reproduce

Stopped 'Area Miner' with the button "Stop and delete"

Pressed add on the 'Follower' plugin and tried to make it follow me.

Got this error 
<img width="746" alt="image" src="https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/80c0ff73-3c32-4263-a3e7-1e2bcbdac5d2">

### Screenshots

My settings
<img width="767" alt="image" src="https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/f543dee9-e27e-4e42-90ce-cbb220235a5f">

<img width="760" alt="image" src="https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/32a517ec-eb5e-452c-9e53-5c529968bcff">

### Profile/Snapshot

Reporting user support id: - 0-rjf8e96k

Reporting profile id: - 661d2b683f4b050282fb6c57

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Fixed in build #b-2024-04-24-a
