### ISSUE TITLE
[Web/Bug]: Inventory container not show the correct item.

### ISSUE THREAD

**Issue by 599ms** [MinecraftBot-com/MineBot-V3-Issues#21]
### Current Behavior

The inventory container is not showing the correct item.

Or the buttons have different functions. 

No matter what the button is not doing what it says so.

Server - "mc.onlineklubben.dk"
Version - 1.20.4

### Expected Behavior

it should use the "left click" as of the buttons name.

it also shows two items in the same slot. It does not give it to the other hand.

### Steps To Reproduce

Press on my bots head, head over to the inventory container. Try and use the "Left click" button but it switches to another item. The item is in the inventory but I can't see it.

### Screenshots

https://streamable.com/pqo725

### Profile/Snapshot

Reporting user support id: - 0-rjf8e96k

Reporting profile id: - 661d2b683f4b050282fb6c57

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Clarity improved in build #b-2024-04-24-a
