### ISSUE TITLE
[Feature]: Remembering account data

### ISSUE THREAD

**Issue by mika0305** [MinecraftBot-com/MineBot-V3-Issues#22]
### Description

After you made your first profile and added accounts to it it saves the account data. If you want to make an new profile you can re-add the accounts to the profile instead of logging in with microsoft again.

### Suggested Solution

Maybe add an section to the dropdown with saved accounts that has checkboxes per account that has been added before.

### Alternatives

If its not possible the email and password list would be fine. But that is disabled for now.

### Additional Context

-

**Comment by OnlyQubes** [comment]
Added in build #b-2024-04-24-a
