### ISSUE TITLE
[Feature]: Cobblestone generator multiple points

### ISSUE THREAD

**Issue by 599ms** [MinecraftBot-com/MineBot-V3-Issues#23]
### Description

It could be nice to have more than one spot to mine at. 

Right now it will automatic choose which one to pick and keep breaking that one.

### Suggested Solution

Add a button for multiple spots for the cobblestone generator if you have more than one.
https://streamable.com/a5kdji

### Alternatives

Make it automatic turn around and mine both or more.

**Comment by OnlyQubes** [comment]
Hi, seems like the video got removed, could you post a picture of what you have in mind?

Will be addressing this in update `b-2024-04-24-a`

**Comment by 599ms** [comment]
Yeah, 
<img width="1552" alt="image" src="https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/786726f6-a05f-4ba9-b554-e9a71aa252a1">
Here is a picture where the bot will stand in the middle of the two generators. it could be nice to make it mine both and not just one. Right now it only focuses on one generator.

**Comment by OnlyQubes** [comment]
Added in build #b-2024-04-24-a
