### ISSUE TITLE
[Feature]: Cobblestone generator Farmer - Pickaxe missing

### ISSUE THREAD

**Issue by 599ms** [MinecraftBot-com/MineBot-V3-Issues#24]
### Description

Make so you can setup a webhook or other notification settings if the bot is missing a pickaxe.

The only way to see why has stopped is going into the plugin and see the bot is missing a pickaxe.

### Suggested Solution

Webhook or other notification settings for the plugin.

Could also be overall notifications as if I have stopped the bot or other things.

**Comment by OnlyQubes** [comment]
Feature has been added, adding a picture below of what to expect.
This feature will be available in build #b-2024-04-24-a

![image](https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/13767563/21dfd088-2e0a-49bb-9ab0-b11dd0157ba1)
