### ISSUE TITLE
[Web/Bug]: idk how to say

### ISSUE THREAD

**Issue by WUWOAOWUW** [MinecraftBot-com/MineBot-V3-Issues#25]
### Screenshots

https://gyazo.com/7a26b67e2770c109565edd1c5b04ad93

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Could you elaborate on the issue? Not sure what the issue from the video.
