### ISSUE TITLE
[Bot/Bug]:  some server can't join

### ISSUE THREAD

**Issue by WUWOAOWUW** [MinecraftBot-com/MineBot-V3-Issues#26]
### Current Behavior

i use 1.8

### Screenshots

![image](https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/167145792/073235f1-42a4-483a-bd67-855138fd24af)

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Fixed in build #b-2024-04-24-a
