### ISSUE TITLE
[Feature]: show user name

### ISSUE THREAD

**Issue by WUWOAOWUW** [MinecraftBot-com/MineBot-V3-Issues#27]
### Description

a

### Suggested Solution

a

### Alternatives

a

### Additional Context

![image](https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/167145792/1f35f681-bd7d-462b-ac35-dc7f96b14f0d)

**Comment by OnlyQubes** [comment]
Implemented in build `b-2024-05-06-a`
