### ISSUE TITLE
[Bot/Bug]: Internal Exception encountered

### ISSUE THREAD

**Issue by 599ms** [MinecraftBot-com/MineBot-V3-Issues#28]
### Current Behavior

Reason: Internal Exception encountered. Report issue with Trace Id 1d1cfa72-d650-442e-9295-f7c9497d5fef

Used Ore miner, randomly it just kicked me with that error.

IP - Space-Craft.online
Subserver - /server prison
Protocol - 1.18.2

### Expected Behavior

Should not have been kicked

### Steps To Reproduce

Enabled ore miner. The bot have mined for around 5 minutes before it got kicked.

### Screenshots

<img width="605" alt="image" src="https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/99dbfa79-4923-4de2-9b44-831008d97f5a">

<img width="268" alt="image" src="https://github.com/MinecraftBot-com/MineBot-V3-Issues/assets/83479466/24e3d6e3-8989-48e1-aa93-e4a7ba5d122e">

**Comment by OnlyQubes** [comment]
Fixed in build `b-2024-05-06-a` (under changelog entry `Fixed other obscure crashes[#28]`)
