### ISSUE TITLE
[Bot/Bug]: Crashed bot

### ISSUE THREAD

**Issue by UncouthVampire** [MinecraftBot-com/MineBot-V3-Issues#32]
### Current Behavior

It appears the bot has crashed currently. What was clicked is in the profile of an account, in their inventory, I clicked hold and use, with no free spots in the hot bar(the bot was in a hole apparently when I dropped it's hotbar), and it crashed.

Account ID: 665b611a8e732057a41a7dcd
Support ID:  0-963jks7a

### Steps To Reproduce

Connect to any server, have hotbar full, click hold an use in inventory of a bot on an item not in hotbar

### Profile/Snapshot

Reporting user support id: 0-963jks7a

Reporting profile id: 665b611a8e732057a41a7dcd

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Fixed in build #b-2024-05-31-a
