### ISSUE TITLE
[Bot/Bug]: Ore Miner

### ISSUE THREAD

**Issue by UncouthVampire** [MinecraftBot-com/MineBot-V3-Issues#33]
### Current Behavior

When mining diamonds on 1.20.4, it mines 1 diamond, and than stops mining.

### Expected Behavior

Ore miner continues mining ores.

### Steps To Reproduce

I have it connected to my private paper server on 1.20.4 that I created just to test the bot, each bot has a netherite pickaxe, when turning on ore miner, it mines 1 diamond only, and than stops mining anything.

### Profile/Snapshot

Reporting user support id: 0-963jks7a

Reporting profile id: 665b611a8e732057a41a7dcd

Profile snapshot: -

**Comment by UncouthVampire** [comment]
More to this plugin problems: Anything that doesn't occupy a full block(grass, bamboo, leaves, etc), the bot doesn't seem to understand how to target it, and break it... Deposit to specific chest also doesn't seem to track to the coordinates, just tells no chest found

**Comment by OnlyQubes** [comment]
First issue fixed in build `b-2024-05-31-a`

**Comment by OnlyQubes** [comment]
Fixed bot ignoring blocks without colliders (but with shapes) (in this case snow) in build `b-2024-06-11-a`

**Comment by OnlyQubes** [comment]
In regards to the last issue (`Deposit to specific chest also doesn't seem to track to the coordinates, just tells no chest found`), there was an issue where Store At Specific Chest wasn't using endless pathing mode, which means that it would fail if the chest was not close enough for the path to be computed in one go. That has been fixed now.
However the Deposito at Specific Chest/Closest Chest should not be used for plugins that may move far away from the starting point, such as Area Miner or Ore Miner, for that you should use Macros (when they are released). To make this more clear the options will be disabled for such plugins starting with build `b-2024-06-11-a`.
