### ISSUE TITLE
[Bot/Bug]: Bot Crashing

### ISSUE THREAD

**Issue by UncouthVampire** [MinecraftBot-com/MineBot-V3-Issues#34]
### Current Behavior

Just trying to start a profile, and it's crashing the bot

### Expected Behavior

Click start bot, and it starts, bot not starting, just crashing:

Server Profile: sn-7TQDW926G
Support ID:  0-963jks7a

### Steps To Reproduce

UV5 profile, just trying to start the bot
Bot Server Restarted, stopping profile. Crash trace: 033aa100
Bot Server Restarted, stopping profile. Crash trace: 52f561f1
Bot Server Restarted, stopping profile. Crash trace: 451770a4

### Profile/Snapshot

Reporting user support id: 665a74418e732057a41a7a29

Reporting profile id: 6660fc0b0941b364ff8ab21a

Profile snapshot: sn-7TQDW926G

**Comment by OnlyQubes** [comment]
Issue was related to networking infrastructure changes, it has been fixed now.
