### ISSUE TITLE
[Feature]: bedrock account

### ISSUE THREAD

**Issue by WUWOAOWUW** [MinecraftBot-com/MineBot-V3-Issues#39]
### Description

some can join the server using bedrock
want to use it for AFK mob farm

### Suggested Solution

a

### Alternatives

a

### Additional Context

a

**Comment by yemix** [comment]
Do you mean crossplay servers? If yes idk how the anti cheat kicks in.

**Comment by OnlyQubes** [comment]
Bedrock support is planned once most features for the current bot are implemented and perfect. There will be a separate post made in the future with mode details, for now closing issue, as it falls out of scope for the current version of the bot, and will only be relevant in the far future.
