### ISSUE TITLE
[Bot/Bug]: CosmicSky Chatcolors in chat function

### ISSUE THREAD

**Issue by Qeewt** [MinecraftBot-com/MineBot-V3-Issues#41]
### Current Behavior

On the dashboard page when you click on a account and choose chat function the chat color codes are getting colored correctly as shown below in the screenshots.

![image](https://github.com/user-attachments/assets/00993115-c907-48fa-8dca-94a2bee18b07)
![image](https://github.com/user-attachments/assets/ed4b2194-0114-48e3-a163-8d7d164547c1)

### Expected Behavior

The chat colors should be getting correctly colored in chat function instead of just showing the raw chat colors codes

### Steps To Reproduce

Not 100% sure what triggers it but it works fine until something in chat gets sent and it just corrupts everything and none of the colorcodes works as they should anymore.
Colors just aren't getting colored and getting sent in raw text.

### Screenshots

![image](https://github.com/user-attachments/assets/095b11ad-36d6-4d71-9896-720f4bc7ca6f)
![image](https://github.com/user-attachments/assets/3ea36ae8-4131-4526-9d3f-aa74dc7b4763)
(same message)

### Profile/Snapshot

Reporting user support id: - 0-zgq6gd1y

Reporting profile id: - 665a2cdd8e732057a41a7463

Profile snapshot: - Auto - 1.20.4

### Additional Context

IP: cosmicsky.net
Version 1.20.4

**Comment by OnlyQubes** [comment]
Fixed in pre-prod-2024-09-12a
