### ISSUE TITLE
[Bot/Bug]: Macros, Wait component.

### ISSUE THREAD

**Issue by Qeewt** [MinecraftBot-com/MineBot-V3-Issues#46]
### Current Behavior

Current max wait duration is 360000 ms (6min).
![image](https://github.com/user-attachments/assets/72b4c0b8-0e3e-421b-991f-31007b1bc1bd)

### Expected Behavior

Should be uncapped or atleast way higher max duration.

### Screenshots

![image](https://github.com/user-attachments/assets/7d62a7c8-1a37-4222-9e04-4275e8a1be4d)

### Profile/Snapshot

Reporting user support id: - 0-zgq6gd1y

Reporting profile id: - 665a2cdd8e732057a41a7463

Profile snapshot: - Auto - 1.20.4

**Comment by OnlyQubes** [comment]
Increased max duration for Wait component from 6 minutes to 1 hour in patch `pre-prod-2024-09-03a`
