### ISSUE TITLE
[Bot/Bug]: 

### ISSUE THREAD

**Issue by Kevin081599** [MinecraftBot-com/MineBot-V3-Issues#59]
### Current Behavior

Hit start bot and it just spins and never starts.

### Expected Behavior

The bot go start

### Steps To Reproduce

25964399

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -25964399

**Comment by OnlyQubes** [comment]
Looking into this right now.

**Comment by OnlyQubes** [comment]
Resolved, license time will be compensated. If you are still experiecing issues please email us at help@minecraftbot.com
