### ISSUE TITLE
[Bot/Bug]: Join game message not working

### ISSUE THREAD

**Issue by Hausi1980** [MinecraftBot-com/MineBot-V3-Issues#67]
### Current Behavior

Hello, the join game message is not working since today. My 18 bots still standing on same place

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Thanks for the bug report. Issue has been identified and fixed. Fix will be released in 12 hours, sorry for the inconvenience.
