### ISSUE TITLE
[Bot/Bug]: Plugins Not working

### ISSUE THREAD

**Issue by Larsen140** [MinecraftBot-com/MineBot-V3-Issues#70]
### Current Behavior

I have a macro it always worked but since yesterday and without macros they arent doing any plugins anymore can ya help me?

### Expected Behavior

They should auto eat and cobble stone farm

### Steps To Reproduce

Plugin is not working

### Profile/Snapshot

sn-8K4A0BFXX

**Comment by OnlyQubes** [comment]
Thanks for the bug report. Issue has been identified and fixed. Fix will be released in 12 hours, sorry for the inconvenience.
