### ISSUE TITLE
[Bot/Bug]: welcome message after Server restart fail

### ISSUE THREAD

**Issue by Hausi1980** [MinecraftBot-com/MineBot-V3-Issues#72]
### Current Behavior

Since around 3-4 days i have the problem that the bots welcome message did Not work after server restart and the bots dont stand on their positions.
Our server restarts every day, so this problem happened not only once.

When i stop and start the bot everything works. But after server restart something is wrong.
Please check it6.

Thank you 

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by Hausi1980** [comment]
Ah, i know exact whats the problem. 

The world will be resetted every day and the bots dont check that they were moved to another place. 

Can you please add a "world change checker" to get back to the correct home spot? *

**Comment by Hausi1980** [comment]
*so that the bot can send welcome message again?!?

**Comment by OnlyQubes** [comment]
Hi,

The "Join Game Message" setting only sends messages when the bot connects to the server for the first time, it does not detect being sent to the hub, or switching worlds.
If you would like to send chat commands/do actions when the bot is sent back to the hub, then you should use Macros. There is a macro component called `Teleport Event` which can be used to detect bot switching worlds. In addition to that you can also use a `Is At Location` component to check if the bot is in the hub. **The most primitive and simple macro approach would look something like this:**
![image](https://github.com/user-attachments/assets/e2ba2ca3-81c0-4bc1-98df-e46c78763a9a)

_Note how Settings > Loop is set to `Infinitely Loop`_
