### ISSUE TITLE
[Bot/Bug]: 

### ISSUE THREAD

**Issue by Pott1ng** [MinecraftBot-com/MineBot-V3-Issues#73]
### Current Behavior

my bot is disconnecting every 2mins with 1 of the following reponses how do i fix this

MutedCorruptedFrameException : Frame too big

Reason: Disconnected

MutedCorruptedFrameException : Packet smaller then threshold 90 / 256

Reason: MutedCorruptedFrameException : (max-decompressed-packet-length in XCord.yml) Packet exceeds 2097152bytes in size: 22709358

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by OnlyQubes** [comment]
Hi,

Could you provide the Profile id (can be in the URL), and your User support id (can be found at https://dashboard.minecraftbot.com/account). Need to see what protocol you are using, and what server is this on. Also if there are any steps necessary to reproduce the disconnect (e.g.: teleporting to a specific location),  then it would be good to know as well.
