### ISSUE TITLE
[Bot/Bug]: System Crashed, contact Support if issue persists

### ISSUE THREAD

**Issue by Hausi1980** [MinecraftBot-com/MineBot-V3-Issues#75]
### Current Behavior

Hello, since around 2 days i have the problem that one of my bot profile crashes.

Please check it.

Thank you 
![Screenshot_20241117-183536](https://github.com/user-attachments/assets/bea92757-9c5a-4a16-be0d-4d8869c19de7)

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by Hausi1980** [comment]
Profile 66ed33bc5767ff2c79030105

**Comment by OnlyQubes** [comment]
Seems like you have two profiles active, has this issue been resolved?

**Comment by Hausi1980** [comment]
no its not. This morning it was again :-(

**Comment by Hausi1980** [comment]
One profile is running fine, the other crashes around 2 times a day

**Comment by Hausi1980** [comment]
Today it crashed again

**Comment by OnlyQubes** [comment]
When it crashes could you please not restart the profile again, would like to look into the containers exit code and last logs, however it gets cleared when you restart the profile. Email me at OnlyQubes@gmail.com when the crash happens and I'll look into the logs. Thanks.

**Comment by Hausi1980** [comment]
I send you an Email now, because it crashed
