### ISSUE TITLE
[Web/Bug]: When I try to access one of the profiles, it keeps quiting to the dashboard, any way to fix it?

### ISSUE THREAD

**Issue by asdadsdsadsaadsfastest** [MinecraftBot-com/MineBot-V3-Issues#77]
### Current Behavior

It keeps closing when I try to select a profile.

### Expected Behavior

I press dashboard.
Then I clicked one of the profiles.
And then it just sends me to the profiles.
![Screen Shot 2024-12-11 at 5 57 29 PM](https://github.com/user-attachments/assets/11d6ff6b-8170-4a96-a2e2-03a9e95982a5)
![Screen Shot 2024-12-11 at 5 57 15 PM](https://github.com/user-attachments/assets/de002f73-2b93-4a0a-a2d7-cb2dedadc515)

### Steps To Reproduce

Go on profiles.
Try to click on one of the profiles.
Then it instantly closes.
Why?

### Profile/Snapshot

Reporting user support id: -
...
Reporting profile id: -
All of mine, don't know how to get.
Profile snapshot: -
1.20.4

### Additional Context

...

**Comment by asdadsdsadsaadsfastest** [comment]
Help?????????

**Comment by OnlyQubes** [comment]
Hi,

Sorry about that, there was an issue with a patch released a few days ago. It should be good now, let me know if you the issue still persists.
